### ISSUE TITLE
Привіт друзі!

### ISSUE THREAD

**Issue by Wandalen** [rust-lang-ua/rust-book-uk-ua#3]
Привіт, чудова ініціатива!
Як стосовно того щоб оживити проект?
Чи знаєте ви про інші подібні ініціативи?

**Comment by pavloslav** [comment]
Привіт.
Можу сказати, чому я закинув (окрім часу, звісно): відсутність інших зацікавлених людей. Словотворення постійно викликало у мене проблеми, а оскільки перекладав я один, то не міг зупинитися на одному терміні і постійно крутився, переробляючи один і той самий розділ (див. DICTIONARY.md).

Якщо буде бажання взяти участь - готовий повернутися.

А, ще пів року тому один тип перебрав на себе посилання з офіційного Rust Book, але швидко здувся: https://github.com/Arideno/rust-book-uk
Можна його теж запросити. Хоча тоді на мій лист він не відповів.

**Comment by Wandalen** [comment]
Файлно 😃 !
Нас в організації досить багато: https://github.com/rust-lang-ua
Напиши, будь ласка, мені в телеграм @wandalen_me або скажи як з тобою зв'язатися.
Мені хотілося б допомогти тобі відновити цю потрібну справу та залучити до цього більше людей із нашої спільноти. В спільноті наразі 450 людей.
